### PR TITLE
Minimal fix for unneccessary JSON AST creation

### PR DESCRIPTION
**Pull request by benjamin-actyx**
As https://github.com/Actyx/wsrpc/pull/1 has stalled, here’s a working (I believe) fix that isn’t very pretty but works.

### CODE REVIEW

**Review by rklaehn — APPROVED** [review]
Interesting. I was trying to use RawValue as well, but I ran into some issues.

serde_json::RawValue is buggy and needs to be used with care, as I unfortunately had to find out. But it seems this particular usage does not trigger the bug.

**Comment by rklaehn** [comment]
I think I tried to use RawValue in both incoming and outgoing, which triggered the bug.

Here is the bug: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4d9015b013535f143aa5b8ad829be43c

**Review by aruediger — APPROVED** [review]
I was just going to mention https://github.com/Actyx/Cosmos/issues/6202#issuecomment-824817563 as well. I assume you've tried it with the actyx API so 👍 .

**Comment by rklaehn** [comment]
I created an issue in serde, but I don't expect this to be fixed: https://github.com/serde-rs/json/issues/779

The way serde is implemented it is basically impossible to implement something like RawValue. The serde_json RawValue is an extremely ugly hack which never really worked.

Makes your eyes bleed. I remember Endre complaining about this...
https://github.com/serde-rs/json/blob/master/src/raw.rs#L278

In libipld we got a *proper* RawValue....

**Comment by benjamin-actyx** [comment]
>But it seems this particular usage does not trigger the bug.

Hmm, what’s the decisive difference to your reproducer?

**Comment by rklaehn** [comment]
> > But it seems this particular usage does not trigger the bug.
> 
> Hmm, what’s the decisive difference to your reproducer?

I think you are only trying to write, not read. Writing is unproblematic. But that is also fine, since using serde_json::Value for *incoming* requests is probably fine. The performance problem is for outgoing responses, which can be a lot, right?

**Comment by benjamin-actyx** [comment]
Aah, you are trying to deserialize 'directly' into a `Box<RawValue>`, and that does not work. I get it.

**Pull request merged**
